// <auto-generated />
using System;
using CoreService_backend.DataAccess.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreServicebackend.Migrations
{
    [DbContext(typeof(CoreServiceContext))]
    [Migration("20230214110359_AddRepeatPropertyToResource")]
    partial class AddRepeatPropertyToResource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreService_backend.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAdress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<TimeSpan>("Repeat")
                        .HasColumnType("time");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IpAdress = "127.0.0.1",
                            Name = "LocalHost",
                            Repeat = new TimeSpan(0, 0, 0, 0, 0),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            IpAdress = "187.166.70.216",
                            Name = "My private website",
                            Repeat = new TimeSpan(0, 0, 0, 0, 0),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            IpAdress = "40.214.147.21",
                            Name = "Some adress",
                            Repeat = new TimeSpan(0, 0, 0, 0, 0),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            IpAdress = "26.252.235.19",
                            Name = "My email service",
                            Repeat = new TimeSpan(0, 0, 0, 0, 0),
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            IpAdress = "127.0.0.1",
                            Name = "Shop website",
                            Repeat = new TimeSpan(0, 0, 0, 0, 0),
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            IpAdress = "175.189.43.59",
                            Name = "Coffee website",
                            Repeat = new TimeSpan(0, 0, 0, 0, 0),
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            IpAdress = "148.143.234.67",
                            Name = "My car rent website",
                            Repeat = new TimeSpan(0, 0, 0, 0, 0),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("CoreService_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "example@email.org",
                            Name = "Antony",
                            Password = "Example1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "example2@gmail.org",
                            Name = "Adam",
                            Password = "Example2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "example3@gmail.org",
                            Name = "Maciej",
                            Password = "Example3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "example4@gmail.org",
                            Name = "Ryszard",
                            Password = "Example4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "example5@gmail.org",
                            Name = "Piotr",
                            Password = "Example5"
                        },
                        new
                        {
                            Id = 6,
                            Email = "example6@gmail.org",
                            Name = "Natalia",
                            Password = "Example6"
                        },
                        new
                        {
                            Id = 7,
                            Email = "example6@gmail.org",
                            Name = "Karolina",
                            Password = "Example6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
